version: "2"
services:
  publish:
    build: ./.docker
    volumes:
    - "./src:/tmp/src"
    - "~/.aws:/root/.aws"
    environment:
    - "AWS_PROFILE=${AWS_PROFILE}"
    working_dir: /tmp/src
    command: "publish"

  viewer:
    build: ./.docker
    volumes:
    - "./src:/tmp/src"
    ports:
    - "4000:4000"
    working_dir: /tmp/src
    command: "serve"
